packages:
  - packages/**
shamefullyHoist: true
shellEmulator: true

catalogs:
  dev:
    "@coderwyd/eslint-config": ^4.11.1
    "@types/node": ^24.10.0
    "@vitejs/plugin-vue": ^6.0.4
    eslint: ^10.0.2
    oxfmt: ^0.36.0
    tsx: ^4.20.6
    typescript: ^5.9.3
    unocss: ^66.6.4
    vite: ^7.3.1
    vue-tsc: ^3.2.5

  prod:
    vue: ^3.5.29
